platform :ios, '8.0'
inhibit_all_warnings!

target "PrisonerFitnessRecord" do
 use_frameworks!
 pod "AFNetworking", "~> 3.0"
 pod 'SDWebImage', '~> 3.8'
 pod 'MJRefresh'
 pod 'Masonry'
 pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
 pod 'MJExtension'
 pod 'JKDBModel-JDBR', '~> 0.0.1'
 pod 'IQKeyboardManager'
 pod ‘pop’
 pod 'PKRevealController'
end
